name: Postman Collection

on:
  workflow_dispatch:

jobs:
  run_postman_collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Directory
        run: |
          mkdir testReports

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run "myCollection.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export testReports/report.html
      
      - name: Upload the results
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: testReports
