name: Postman Collection Using Env

on:
  workflow_dispatch:

jobs:
  run_postman_collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Directory
        run: |
          mkdir testReports

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra
          
      - name: Set environment variables
        run: |
          echo "export MY_APIGW_USERNAME=$MY_APIGW_USERNAME" >> $GITHUB_ENV
          echo "export MY_APIGW_PASSWORD=$MY_APIGW_PASSWORD" >> $GITHUB_ENV

      - name: Run Postman Collection
        run: |
          newman run "myCollection_1.postman_collection.json" --env-var "username=$MY_APIGW_USERNAME" --env-var "password=$MY_APIGW_PASSWORD" -r cli,htmlextra --reporter-htmlextra-export testReports/report.html
        env:
          MY_APIGW_USERNAME: ${{ secrets.MY_APIGW_USERNAME }}
          MY_APIGW_PASSWORD: ${{ secrets.MY_APIGW_PASSWORD }}
      
      - name: Upload the results
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: testReports
