name: create-release
on:
  workflow_dispatch:
jobs:
  -name: Create GitHub Release
   id: create-new-release
   uses: actions/create-release@v1
   env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   with:
    tag_name: ${{ github.run_number }}
    release_name: Release ${{ github.run_number }}
      
 
