name: zip-artifact
on: [push]
env:
  zipFileName: testFile.zip
  zipFilePath: ./src/apis/testFile
  name: my-artifact
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p ${{ github.workspace }}/artifact
          echo hello > ${{ github.workspace }}/artifact/world.txt
          ls -r
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}-name
          path: ${{ github.workspace }}/artifact/**/*  
       
      
